import matplotlib.pyplot as plt
import numpy as np

data_1 = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30]
data_goukei = [10,17,19,23,31,41,43,47,53,57,59,61,65,66,67,69,70,73,74,77,78,80,81,83,85,87,88,89,92,93]
a=1
b=2
c=3
d=4
data_A = [a,b,c,d,a,c,a,c,d,b,b,b,c,b,d,d,d,a,b,c,a,d,b,c,d,c,d,a,b,c]
data_B = [c,b,d,d,d,c,b,c,a,b,c,d,c,d,c,b,c,b,c,b,a,a,a,d,c,d,c,b,c,b]
data_C = [a,b,c,d,a,a,a,c,d,b,b,b,c,b,d,d,d,a,b,c,a,d,b,c,d,c,d,a,b,c]
data_D = [a,b,c,d,a,a,a,c,d,b,b,b,c,b,d,d,d,a,b,c,a,d,b,c,d,c,d,a,b,c]
data_E = [a,b,c,c,a,b,a,c,d,b,a,b,c,b,d,c,d,a,b,c,a,d,b,c,d,c,d,a,b,c]
data_F = [a,b,c,d,a,a,a,c,d,a,b,b,c,b,d,d,d,a,b,c,a,b,b,c,d,c,d,a,b,c]
data_G = [a,b,c,d,a,a,a,c,d,b,b,b,c,b,d,d,d,a,b,c,a,d,b,c,d,c,d,a,b,c]
data_H = [a,b,c,d,a,a,a,c,d,b,b,b,c,b,d,d,d,a,b,c,a,d,b,c,d,c,d,a,b,c]
#----------問題の答え-------------
data_A_ans = 1
data_B_ans = 1
data_C_ans = 1
data_D_ans = 1
data_E_ans = 1
data_F_ans = 1
data_G_ans = 1
data_H_ans = 1
#--------------合計点によって郡に分ける------------------
n = 5
data1 = data_goukei[:n+1]
data2 = data_goukei[n+1:n+7]
data3 = data_goukei[n+7:n+13]
data4 = data_goukei[n+13:n+19]
data5 = data_goukei[n+19:n+25]
#--------------郡ごとの問題に対する答え------------------
#(A)
data_A_1 = data_A[:n+1]
data_A_2 = data_A[n+1:n+7]
data_A_3 = data_A[n+7:n+13]
data_A_4 = data_A[n+13:n+19]
data_A_5 = data_A[n+19:n+25]
#(B)
data_B_1 = data_B[:n+1]
data_B_2 = data_B[n+1:n+7]
data_B_3 = data_B[n+7:n+13]
data_B_4 = data_B[n+13:n+19]
data_B_5 = data_B[n+19:n+25]
#(C)
data_C_1 = data_C[:n+1]
data_C_2 = data_C[n+1:n+7]
data_C_3 = data_C[n+7:n+13]
data_C_4 = data_C[n+13:n+19]
data_C_5 = data_C[n+19:n+25]
#(D)
data_D_1 = data_D[:n+1]
data_D_2 = data_D[n+1:n+7]
data_D_3 = data_D[n+7:n+13]
data_D_4 = data_D[n+13:n+19]
data_D_5 = data_D[n+19:n+25]
#(E)
data_E_1 = data_E[:n+1]
data_E_2 = data_E[n+1:n+7]
data_E_3 = data_E[n+7:n+13]
data_E_4 = data_E[n+13:n+19]
data_E_5 = data_E[n+19:n+25]
#(F)
data_F_1 = data_F[:n+1]
data_F_2 = data_F[n+1:n+7]
data_F_3 = data_F[n+7:n+13]
data_F_4 = data_F[n+13:n+19]
data_F_5 = data_F[n+19:n+25]
#(G)
data_G_1 = data_G[:n+1]
data_G_2 = data_G[n+1:n+7]
data_G_3 = data_G[n+7:n+13]
data_G_4 = data_G[n+13:n+19]
data_G_5 = data_G[n+19:n+25]
#(H)
data_H_1 = data_H[:n+1]
data_H_2 = data_H[n+1:n+7]
data_H_3 = data_H[n+7:n+13]
data_H_4 = data_H[n+13:n+19]
data_H_5 = data_H[n+19:n+25]
#--------------問題に対して正しい選択肢を選んだ確率------------------
#(A)
#(a)
data_A_1_theta_1 = int(format(data_A_1.count(1))) / len(data_A_1)
data_A_2_theta_1 = int(format(data_A_2.count(1))) / len(data_A_2)
data_A_3_theta_1 = int(format(data_A_3.count(1))) / len(data_A_3)
data_A_4_theta_1 = int(format(data_A_4.count(1))) / len(data_A_4)
data_A_5_theta_1 = int(format(data_A_5.count(1))) / len(data_A_5)
#(b)
data_A_1_theta_2 = int(format(data_A_1.count(2))) / len(data_A_1)
data_A_2_theta_2 = int(format(data_A_2.count(2))) / len(data_A_2)
data_A_3_theta_2 = int(format(data_A_3.count(2))) / len(data_A_3)
data_A_4_theta_2 = int(format(data_A_4.count(2))) / len(data_A_4)
data_A_5_theta_2 = int(format(data_A_5.count(2))) / len(data_A_5)
#(c)
data_A_1_theta_3 = int(format(data_A_1.count(3))) / len(data_A_1)
data_A_2_theta_3 = int(format(data_A_2.count(3))) / len(data_A_2)
data_A_3_theta_3 = int(format(data_A_3.count(3))) / len(data_A_3)
data_A_4_theta_3 = int(format(data_A_4.count(3))) / len(data_A_4)
data_A_5_theta_3 = int(format(data_A_5.count(3))) / len(data_A_5)
#(d)
data_A_1_theta_4 = int(format(data_A_1.count(4))) / len(data_A_1)
data_A_2_theta_4 = int(format(data_A_2.count(4))) / len(data_A_2)
data_A_3_theta_4 = int(format(data_A_3.count(4))) / len(data_A_3)
data_A_4_theta_4 = int(format(data_A_4.count(4))) / len(data_A_4)
data_A_5_theta_4 = int(format(data_A_5.count(4))) / len(data_A_5)

#(B)
#(a)
data_B_1_theta_1 = int(format(data_B_1.count(1))) / len(data_A_1)
data_B_2_theta_1 = int(format(data_B_2.count(1))) / len(data_A_2)
data_B_3_theta_1 = int(format(data_B_3.count(1))) / len(data_A_3)
data_B_4_theta_1 = int(format(data_B_4.count(1))) / len(data_A_4)
data_B_5_theta_1 = int(format(data_B_5.count(1))) / len(data_A_5)
#(b)
data_B_1_theta_2 = int(format(data_B_1.count(2))) / len(data_A_1)
data_B_2_theta_2 = int(format(data_B_2.count(2))) / len(data_A_2)
data_B_3_theta_2 = int(format(data_B_3.count(2))) / len(data_A_3)
data_B_4_theta_2 = int(format(data_B_4.count(2))) / len(data_A_4)
data_B_5_theta_2 = int(format(data_B_5.count(2))) / len(data_A_5)
#(c)
data_B_1_theta_3 = int(format(data_B_1.count(3))) / len(data_A_1)
data_B_2_theta_3 = int(format(data_B_2.count(3))) / len(data_A_2)
data_B_3_theta_3 = int(format(data_B_3.count(3))) / len(data_A_3)
data_B_4_theta_3 = int(format(data_B_4.count(3))) / len(data_A_4)
data_B_5_theta_3 = int(format(data_B_5.count(3))) / len(data_A_5)
#(d)
data_B_1_theta_4 = int(format(data_B_1.count(4))) / len(data_A_1)
data_B_2_theta_4 = int(format(data_B_2.count(4))) / len(data_A_2)
data_B_3_theta_4 = int(format(data_B_3.count(4))) / len(data_A_3)
data_B_4_theta_4 = int(format(data_B_4.count(4))) / len(data_A_4)
data_B_5_theta_4 = int(format(data_B_5.count(4))) / len(data_A_5)
#(C)
#(a)
data_C_1_theta_1 = int(format(data_C_1.count(1))) / len(data_A_1)
data_C_2_theta_1 = int(format(data_C_2.count(1))) / len(data_A_2)
data_C_3_theta_1 = int(format(data_C_3.count(1))) / len(data_A_3)
data_C_4_theta_1 = int(format(data_C_4.count(1))) / len(data_A_4)
data_C_5_theta_1 = int(format(data_C_5.count(1))) / len(data_A_5)
#(b)
data_C_1_theta_2 = int(format(data_C_1.count(2))) / len(data_A_1)
data_C_2_theta_2 = int(format(data_C_2.count(2))) / len(data_A_2)
data_C_3_theta_2 = int(format(data_C_3.count(2))) / len(data_A_3)
data_C_4_theta_2 = int(format(data_C_4.count(2))) / len(data_A_4)
data_C_5_theta_2 = int(format(data_C_5.count(2))) / len(data_A_5)
#(c)
data_C_1_theta_3 = int(format(data_C_1.count(3))) / len(data_A_1)
data_C_2_theta_3 = int(format(data_C_2.count(3))) / len(data_A_2)
data_C_3_theta_3 = int(format(data_C_3.count(3))) / len(data_A_3)
data_C_4_theta_3 = int(format(data_C_4.count(3))) / len(data_A_4)
data_C_5_theta_3 = int(format(data_C_5.count(3))) / len(data_A_5)
#(d)
data_C_1_theta_4 = int(format(data_C_1.count(4))) / len(data_A_1)
data_C_2_theta_4 = int(format(data_C_2.count(4))) / len(data_A_2)
data_C_3_theta_4 = int(format(data_C_3.count(4))) / len(data_A_3)
data_C_4_theta_4 = int(format(data_C_4.count(4))) / len(data_A_4)
data_C_5_theta_4 = int(format(data_C_5.count(4))) / len(data_A_5)
#(D)
#(a)
data_D_1_theta_1 = int(format(data_D_1.count(1))) / len(data_A_1)
data_D_2_theta_1 = int(format(data_D_2.count(1))) / len(data_A_2)
data_D_3_theta_1 = int(format(data_D_3.count(1))) / len(data_A_3)
data_D_4_theta_1 = int(format(data_D_4.count(1))) / len(data_A_4)
data_D_5_theta_1 = int(format(data_D_5.count(1))) / len(data_A_5)
#(b)
data_D_1_theta_2 = int(format(data_D_1.count(2))) / len(data_A_1)
data_D_2_theta_2 = int(format(data_D_2.count(2))) / len(data_A_2)
data_D_3_theta_2 = int(format(data_D_3.count(2))) / len(data_A_3)
data_D_4_theta_2 = int(format(data_D_4.count(2))) / len(data_A_4)
data_D_5_theta_2 = int(format(data_D_5.count(2))) / len(data_A_5)
#(c)
data_D_1_theta_3 = int(format(data_D_1.count(3))) / len(data_A_1)
data_D_2_theta_3 = int(format(data_D_2.count(3))) / len(data_A_2)
data_D_3_theta_3 = int(format(data_D_3.count(3))) / len(data_A_3)
data_D_4_theta_3 = int(format(data_D_4.count(3))) / len(data_A_4)
data_D_5_theta_3 = int(format(data_D_5.count(3))) / len(data_A_5)
#(d)
data_D_1_theta_4 = int(format(data_D_1.count(4))) / len(data_A_1)
data_D_2_theta_4 = int(format(data_D_2.count(4))) / len(data_A_2)
data_D_3_theta_4 = int(format(data_D_3.count(4))) / len(data_A_3)
data_D_4_theta_4 = int(format(data_D_4.count(4))) / len(data_A_4)
data_D_5_theta_4 = int(format(data_D_5.count(4))) / len(data_A_5)
#(E)
#(a)
data_E_1_theta_1 = int(format(data_E_1.count(1))) / len(data_A_1)
data_E_2_theta_1 = int(format(data_E_2.count(1))) / len(data_A_2)
data_E_3_theta_1 = int(format(data_E_3.count(1))) / len(data_A_3)
data_E_4_theta_1 = int(format(data_E_4.count(1))) / len(data_A_4)
data_E_5_theta_1 = int(format(data_E_5.count(1))) / len(data_A_5)
#(b)
data_E_1_theta_2 = int(format(data_E_1.count(2))) / len(data_A_1)
data_E_2_theta_2 = int(format(data_E_2.count(2))) / len(data_A_2)
data_E_3_theta_2 = int(format(data_E_3.count(2))) / len(data_A_3)
data_E_4_theta_2 = int(format(data_E_4.count(2))) / len(data_A_4)
data_E_5_theta_2 = int(format(data_E_5.count(2))) / len(data_A_5)
#(c)
data_E_1_theta_3 = int(format(data_E_1.count(3))) / len(data_A_1)
data_E_2_theta_3 = int(format(data_E_2.count(3))) / len(data_A_2)
data_E_3_theta_3 = int(format(data_E_3.count(3))) / len(data_A_3)
data_E_4_theta_3 = int(format(data_E_4.count(3))) / len(data_A_4)
data_E_5_theta_3 = int(format(data_E_5.count(3))) / len(data_A_5)
#(d)
data_E_1_theta_4 = int(format(data_E_1.count(4))) / len(data_A_1)
data_E_2_theta_4 = int(format(data_E_2.count(4))) / len(data_A_2)
data_E_3_theta_4 = int(format(data_E_3.count(4))) / len(data_A_3)
data_E_4_theta_4 = int(format(data_E_4.count(4))) / len(data_A_4)
data_E_5_theta_4 = int(format(data_E_5.count(4))) / len(data_A_5)
#(F)
#(a)
data_F_1_theta_1 = int(format(data_F_1.count(1))) / len(data_A_1)
data_F_2_theta_1 = int(format(data_F_2.count(1))) / len(data_A_2)
data_F_3_theta_1 = int(format(data_F_3.count(1))) / len(data_A_3)
data_F_4_theta_1 = int(format(data_F_4.count(1))) / len(data_A_4)
data_F_5_theta_1 = int(format(data_F_5.count(1))) / len(data_A_5)
#(b)
data_F_1_theta_2 = int(format(data_F_1.count(2))) / len(data_A_1)
data_F_2_theta_2 = int(format(data_F_2.count(2))) / len(data_A_2)
data_F_3_theta_2 = int(format(data_F_3.count(2))) / len(data_A_3)
data_F_4_theta_2 = int(format(data_F_4.count(2))) / len(data_A_4)
data_F_5_theta_2 = int(format(data_F_5.count(2))) / len(data_A_5)
#(c)
data_F_1_theta_3 = int(format(data_F_1.count(3))) / len(data_A_1)
data_F_2_theta_3 = int(format(data_F_2.count(3))) / len(data_A_2)
data_F_3_theta_3 = int(format(data_F_3.count(3))) / len(data_A_3)
data_F_4_theta_3 = int(format(data_F_4.count(3))) / len(data_A_4)
data_F_5_theta_3 = int(format(data_F_5.count(3))) / len(data_A_5)
#(d)
data_F_1_theta_4 = int(format(data_F_1.count(4))) / len(data_A_1)
data_F_2_theta_4 = int(format(data_F_2.count(4))) / len(data_A_2)
data_F_3_theta_4 = int(format(data_F_3.count(4))) / len(data_A_3)
data_F_4_theta_4 = int(format(data_F_4.count(4))) / len(data_A_4)
data_F_5_theta_4 = int(format(data_F_5.count(4))) / len(data_A_5)
#(G)
#(a)
data_G_1_theta_1 = int(format(data_G_1.count(1))) / len(data_A_1)
data_G_2_theta_1 = int(format(data_G_2.count(1))) / len(data_A_2)
data_G_3_theta_1 = int(format(data_G_3.count(1))) / len(data_A_3)
data_G_4_theta_1 = int(format(data_G_4.count(1))) / len(data_A_4)
data_G_5_theta_1 = int(format(data_G_5.count(1))) / len(data_A_5)
#(b)
data_G_1_theta_2 = int(format(data_G_1.count(2))) / len(data_A_1)
data_G_2_theta_2 = int(format(data_G_2.count(2))) / len(data_A_2)
data_G_3_theta_2 = int(format(data_G_3.count(2))) / len(data_A_3)
data_G_4_theta_2 = int(format(data_G_4.count(2))) / len(data_A_4)
data_G_5_theta_2 = int(format(data_G_5.count(2))) / len(data_A_5)
#(c)
data_G_1_theta_3 = int(format(data_G_1.count(3))) / len(data_A_1)
data_G_2_theta_3 = int(format(data_G_2.count(3))) / len(data_A_2)
data_G_3_theta_3 = int(format(data_G_3.count(3))) / len(data_A_3)
data_G_4_theta_3 = int(format(data_G_4.count(3))) / len(data_A_4)
data_G_5_theta_3 = int(format(data_G_5.count(3))) / len(data_A_5)
#(d)
data_G_1_theta_4 = int(format(data_G_1.count(4))) / len(data_A_1)
data_G_2_theta_4 = int(format(data_G_2.count(4))) / len(data_A_2)
data_G_3_theta_4 = int(format(data_G_3.count(4))) / len(data_A_3)
data_G_4_theta_4 = int(format(data_G_4.count(4))) / len(data_A_4)
data_G_5_theta_4 = int(format(data_G_5.count(4))) / len(data_A_5)
#(H)
#(a)
data_H_1_theta_1 = int(format(data_H_1.count(1))) / len(data_A_1)
data_H_2_theta_1 = int(format(data_H_2.count(1))) / len(data_A_2)
data_H_3_theta_1 = int(format(data_H_3.count(1))) / len(data_A_3)
data_H_4_theta_1 = int(format(data_H_4.count(1))) / len(data_A_4)
data_H_5_theta_1 = int(format(data_H_5.count(1))) / len(data_A_5)
#(b)
data_H_1_theta_2 = int(format(data_H_1.count(2))) / len(data_A_1)
data_H_2_theta_2 = int(format(data_H_2.count(2))) / len(data_A_2)
data_H_3_theta_2 = int(format(data_H_3.count(2))) / len(data_A_3)
data_H_4_theta_2 = int(format(data_H_4.count(2))) / len(data_A_4)
data_H_5_theta_2 = int(format(data_H_5.count(2))) / len(data_A_5)
#(c)
data_H_1_theta_3 = int(format(data_H_1.count(3))) / len(data_A_1)
data_H_2_theta_3 = int(format(data_H_2.count(3))) / len(data_A_2)
data_H_3_theta_3 = int(format(data_H_3.count(3))) / len(data_A_3)
data_H_4_theta_3 = int(format(data_H_4.count(3))) / len(data_A_4)
data_H_5_theta_3 = int(format(data_H_5.count(3))) / len(data_A_5)
#(d)
data_H_1_theta_4 = int(format(data_H_1.count(4))) / len(data_A_1)
data_H_2_theta_4 = int(format(data_H_2.count(4))) / len(data_A_2)
data_H_3_theta_4 = int(format(data_H_3.count(4))) / len(data_A_3)
data_H_4_theta_4 = int(format(data_H_4.count(4))) / len(data_A_4)
data_H_5_theta_4 = int(format(data_H_5.count(4))) / len(data_A_5)
#----------------------------グラフの値の生成---------------------
#(A)
#(a)
y_A_1 = np.array([data_A_1_theta_1,data_A_2_theta_1,data_A_3_theta_1,data_A_4_theta_1,data_A_5_theta_1])
#(b)
y_A_2 = np.array([data_A_1_theta_2,data_A_2_theta_2,data_A_3_theta_2,data_A_4_theta_2,data_A_5_theta_2])
#(c)
y_A_3 = np.array([data_A_1_theta_3,data_A_2_theta_3,data_A_3_theta_3,data_A_4_theta_3,data_A_5_theta_3])
#(d)
y_A_4 = np.array([data_A_1_theta_4,data_A_2_theta_4,data_A_3_theta_4,data_A_4_theta_4,data_A_5_theta_4])

#(B)
#(a)
y_B_1 = np.array([data_B_1_theta_1,data_B_2_theta_1,data_B_3_theta_1,data_B_4_theta_1,data_B_5_theta_1])
#(b)
y_B_2 = np.array([data_B_1_theta_2,data_B_2_theta_2,data_B_3_theta_2,data_B_4_theta_2,data_B_5_theta_2])
#(c)
y_B_3 = np.array([data_B_1_theta_3,data_B_2_theta_3,data_B_3_theta_3,data_B_4_theta_3,data_B_5_theta_3])
#(d)
y_B_4 = np.array([data_B_1_theta_4,data_B_2_theta_4,data_B_3_theta_4,data_B_4_theta_4,data_B_5_theta_4])
#(C)
#(a)
y_C_1 = np.array([data_C_1_theta_1,data_C_2_theta_1,data_C_3_theta_1,data_C_4_theta_1,data_C_5_theta_1])
#(b)
y_C_2 = np.array([data_C_1_theta_2,data_C_2_theta_2,data_C_3_theta_2,data_C_4_theta_2,data_C_5_theta_2])
#(c)
y_C_3 = np.array([data_C_1_theta_3,data_C_2_theta_3,data_C_3_theta_3,data_C_4_theta_3,data_C_5_theta_3])
#(d)
y_C_4 = np.array([data_C_1_theta_4,data_C_2_theta_4,data_C_3_theta_4,data_C_4_theta_4,data_C_5_theta_4])
#(D)
#(a)
y_D_1 = np.array([data_D_1_theta_1,data_D_2_theta_1,data_D_3_theta_1,data_D_4_theta_1,data_D_5_theta_1])
#(b)
y_D_2 = np.array([data_D_1_theta_2,data_D_2_theta_2,data_D_3_theta_2,data_D_4_theta_2,data_D_5_theta_2])
#(c)
y_D_3 = np.array([data_D_1_theta_3,data_D_2_theta_3,data_D_3_theta_3,data_D_4_theta_3,data_D_5_theta_3])
#(d)
y_D_4 = np.array([data_D_1_theta_4,data_D_2_theta_4,data_D_3_theta_4,data_D_4_theta_4,data_D_5_theta_4])
#(E)
#(a)
y_E_1 = np.array([data_E_1_theta_1,data_E_2_theta_1,data_E_3_theta_1,data_E_4_theta_1,data_E_5_theta_1])
#(b)
y_E_2 = np.array([data_E_1_theta_2,data_E_2_theta_2,data_E_3_theta_2,data_E_4_theta_2,data_E_5_theta_2])
#(c)
y_E_3 = np.array([data_E_1_theta_3,data_E_2_theta_3,data_E_3_theta_3,data_E_4_theta_3,data_E_5_theta_3])
#(d)
y_E_4 = np.array([data_E_1_theta_4,data_E_2_theta_4,data_E_3_theta_4,data_E_4_theta_4,data_E_5_theta_4])
#(F)
#(a)
y_F_1 = np.array([data_F_1_theta_1,data_F_2_theta_1,data_F_3_theta_1,data_F_4_theta_1,data_F_5_theta_1])
#(b)
y_F_2 = np.array([data_F_1_theta_2,data_F_2_theta_2,data_F_3_theta_2,data_F_4_theta_2,data_F_5_theta_2])
#(c)
y_F_3 = np.array([data_F_1_theta_3,data_F_2_theta_3,data_F_3_theta_3,data_F_4_theta_3,data_F_5_theta_3])
#(d)
y_F_4 = np.array([data_F_1_theta_4,data_F_2_theta_4,data_F_3_theta_4,data_F_4_theta_4,data_F_5_theta_4])
#(G)
#(a)
y_G_1 = np.array([data_G_1_theta_1,data_G_2_theta_1,data_G_3_theta_1,data_G_4_theta_1,data_G_5_theta_1])
#(b)
y_G_2 = np.array([data_G_1_theta_2,data_G_2_theta_2,data_G_3_theta_2,data_G_4_theta_2,data_G_5_theta_2])
#(c)
y_G_3 = np.array([data_G_1_theta_3,data_G_2_theta_3,data_G_3_theta_3,data_G_4_theta_3,data_G_5_theta_3])
#(d)
y_G_4 = np.array([data_G_1_theta_4,data_G_2_theta_4,data_G_3_theta_4,data_G_4_theta_4,data_G_5_theta_4])
#(H)
#(a)
y_H_1 = np.array([data_H_1_theta_1,data_H_2_theta_1,data_H_3_theta_1,data_H_4_theta_1,data_H_5_theta_1])
#(b)
y_H_2 = np.array([data_H_1_theta_2,data_H_2_theta_2,data_H_3_theta_2,data_H_4_theta_2,data_H_5_theta_2])
#(c)
y_H_3 = np.array([data_H_1_theta_3,data_H_2_theta_3,data_H_3_theta_3,data_H_4_theta_3,data_H_5_theta_3])
#(d)
y_H_4 = np.array([data_H_1_theta_4,data_H_2_theta_4,data_H_3_theta_4,data_H_4_theta_4,data_H_5_theta_4])
x = np.array([1,2,3,4,5])
#-------------グラフの位置の設定-----------------
#(A)
fig = plt.figure(figsize=(12, 8))
ax1 = fig.add_subplot(421)
ax1.plot(x,y_A_1, marker="$a$", linewidth= 2, linestyle = "dashed")
ax1.plot(x,y_A_2, marker="$b$", linewidth= 2, linestyle = "dashed")
ax1.plot(x,y_A_3, marker="$c$", linewidth= 2, linestyle = "solid")
ax1.plot(x,y_A_4, marker="$d$", linewidth= 2, linestyle = "dashed")
ax1.set_title("A")
#(B)
ax2 = fig.add_subplot(422)
ax2.plot(x,y_B_1, marker="$a$", linewidth= 2, linestyle = "dashed")
ax2.plot(x,y_B_2, marker="$b$", linewidth= 2, linestyle = "solid")
ax2.plot(x,y_B_3, marker="$c$", linewidth= 2, linestyle = "dashed")
ax2.plot(x,y_B_4, marker="$d$", linewidth= 2, linestyle = "dashed")
ax2.set_title("B")
#(C)
ax3 = fig.add_subplot(423)
ax3.plot(x,y_C_1, marker="$a$", linewidth= 2, linestyle = "dashed")
ax3.plot(x,y_C_2, marker="$b$", linewidth= 2, linestyle = "solid")
ax3.plot(x,y_C_3, marker="$c$", linewidth= 2, linestyle = "dashed")
ax3.plot(x,y_C_4, marker="$d$", linewidth= 2, linestyle = "dashed")
ax3.set_title("C")
#(D)
ax4 = fig.add_subplot(424)
ax4.plot(x,y_D_1, marker="$a$", linewidth= 2, linestyle = "dashed")
ax4.plot(x,y_D_2, marker="$b$", linewidth= 2, linestyle = "solid")
ax4.plot(x,y_D_3, marker="$c$", linewidth= 2, linestyle = "dashed")
ax4.plot(x,y_D_4, marker="$d$", linewidth= 2, linestyle = "dashed")
ax4.set_title("D")
#(E)
ax5 = fig.add_subplot(425)
ax5.plot(x,y_E_1, marker="$a$", linewidth= 2, linestyle = "dashed")
ax5.plot(x,y_E_2, marker="$b$", linewidth= 2, linestyle = "solid")
ax5.plot(x,y_E_3, marker="$c$", linewidth= 2, linestyle = "dashed")
ax5.plot(x,y_E_4, marker="$d$", linewidth= 2, linestyle = "dashed")
ax5.set_title("E")
#(F)
ax6 = fig.add_subplot(426)
ax6.plot(x,y_F_1, marker="$a$", linewidth= 2, linestyle = "dashed")
ax6.plot(x,y_F_2, marker="$b$", linewidth= 2, linestyle = "solid")
ax6.plot(x,y_F_3, marker="$c$", linewidth= 2, linestyle = "dashed")
ax6.plot(x,y_F_4, marker="$d$", linewidth= 2, linestyle = "dashed")
ax6.set_title("F")
#(G)
ax7 = fig.add_subplot(427)
ax7.plot(x,y_G_1, marker="$a$", linewidth= 2, linestyle = "dashed")
ax7.plot(x,y_G_2, marker="$b$", linewidth= 2, linestyle = "solid")
ax7.plot(x,y_G_3, marker="$c$", linewidth= 2, linestyle = "dashed")
ax7.plot(x,y_G_4, marker="$d$", linewidth= 2, linestyle = "dashed")
ax7.set_title("G")
#(H)
ax8 = fig.add_subplot(428)
ax8.plot(x,y_H_1, marker="$a$", linewidth= 2, linestyle = "dashed")
ax8.plot(x,y_H_2, marker="$b$", linewidth= 2, linestyle = "dashed")
ax8.plot(x,y_H_3, marker="$c$", linewidth= 2, linestyle = "dashed")
ax8.plot(x,y_H_4, marker="$d$", linewidth= 2, linestyle = "solid")
ax8.set_title("D")
#----------グラフの生成----------
plt.xticks([ 1,2,3,4,5 ])
plt.tight_layout()
plt.show()
